package se.liu.ida.tdp024.account.rest.util;

import com.sun.jersey.api.core.PackagesResourceConfig;
import java.util.Set;
import javax.ws.rs.ApplicationPath;

@ApplicationPath("/")
public class ApplicationConfiguration extends PackagesResourceConfig {
    
    public ApplicationConfiguration() {
        super("se.liu.ida.tdp024.account.rest.service");
    }

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        // following code can be used to customize Jersey 1.x JSON provider:
        try {
            Class jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(se.liu.ida.tdp024.account.rest.service.AccountService.class);
        resources.add(se.liu.ida.tdp024.account.rest.service.GenericResource.class);
    }
    
}
